"""empty message

Revision ID: 79e769f8e76f
Revises: 
Create Date: 2018-09-05 16:56:31.983872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e769f8e76f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('user_password', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('test_case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_code', sa.String(length=20), nullable=False),
    sa.Column('own_project', sa.String(length=20), nullable=True),
    sa.Column('functional_module', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('batch_type', sa.String(length=20), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('goods_type', sa.String(length=40), nullable=True),
    sa.Column('front_term', sa.String(length=100), nullable=True),
    sa.Column('case_title', sa.String(length=20), nullable=True),
    sa.Column('case_description', sa.String(length=500), nullable=True),
    sa.Column('goods_name', sa.String(length=40), nullable=True),
    sa.Column('expect_result', sa.String(length=500), nullable=True),
    sa.Column('execute_result', sa.String(length=10), nullable=True),
    sa.Column('executive', sa.Integer(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=100), nullable=True),
    sa.Column('execute_log', sa.String(length=500), nullable=True),
    sa.Column('del_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['test_user.user_id'], ),
    sa.ForeignKeyConstraint(['executive'], ['test_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_case')
    op.drop_table('test_user')
    # ### end Alembic commands ###
